from typing import Callable

class RouterBase:
    name: str
    def start(self): ...
    def stop(self): ...
    def publish_telem(self, topic: str, payload: str, qos: int = 0, retain: bool = False): ...
    def subscribe_cmd(self, topic: str, handler: Callable[[str, bytes], None]): ...
