from typing import Optional
from wayfarer.core.packet import Packet

class TransportBase:
    name: str
    def start(self): ...
    def stop(self): ...
    def read(self) -> Optional[Packet]: ...
    def write(self, pkt: Packet): ...
